version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5433:5432
    env_file:
      - app/.env

  app:
    build: .
    command: python manage.py runserver
    ports:
      - 8001:8000
    volumes:
      - ./app:/app
    depends_on:
      - db
    env_file:
      - app/.env
