version: "3.1"

services:
  db:
    image: postgres:11.4
    ports:
    - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - app/.env

  app:
    build: .
    command: /./wait-for-postgres.sh
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    env_file:
      - app/.env

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "44987:44987"
    volumes:
      - ./minio-data:/data
    env_file:
      - app/.env
    command: server /minio-data --console-address ":44987"
