version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - app/.env

  app:
    build: .
    command: /./wait-for-postgres.sh
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    depends_on:
      - db
    env_file:
      - app/.env
