version: "3.1"

services:
  db:
    image: postgres:11.4
    ports:
    - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - app/.env

  app:
    build: .
    command: /./wait-for-postgres.sh
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - minio
    env_file:
      - app/.env

  minio:
    container_name: minio
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio-data:/data
    env_file:
      - app/.env
