version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5433:5432
    env_file:
      - App/.env

  app:
    build: .
    command: python main.py
    ports:
      - 8001:8000
    volumes:
      - ./App:/app
    depends_on:
      - db
    env_file:
      - App/.env
